# Generated by Django 3.2 on 2021-05-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_rename_notification_notification1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.IntegerField()),
                ('employee_name', models.CharField(max_length=30)),
                ('employee_salary', models.FloatField()),
            ],
        ),
    ]
